### ISSUE TITLE
Native Container does not work with Felix 4.2.x. Forked one works fine [PAXEXAM-510]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.exam2#631]
**[Dmytro Pishchukhin](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:75d4dbcd-6ce7-4eba-bea7-c784ab506ce1)** created **[PAXEXAM-510](https://ops4j1.jira.com/browse/PAXEXAM-510)** 

test_Without_OSGiAssertions(org.knowhowlab.osgi.testing.it.paxexam.StyleComparisonIntegrationTest) Time elapsed: 1158 s<br /> ec &lt;&lt;&lt; ERROR!<br /> java.lang.NoSuchMethodError: org.osgi.framework.BundleEvent.&lt;init&gt;(ILorg/osgi/framework/Bundle;Lorg/osgi/framework/Bundl<br /> e;)V<br /> at org.apache.felix.framework.Felix.fireBundleEvent(Felix.java:4408)<br /> at org.apache.felix.framework.Felix.installBundle(Felix.java:3048)<br /> at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:165)<br /> at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:138)<br /> at org.ops4j.pax.exam.nat.internal.NativeTestContainer.installAndStartBundles(NativeTestContainer.java:301)<br /> at org.ops4j.pax.exam.nat.internal.NativeTestContainer.start(NativeTestContainer.java:169)<br /> at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)<br /> at org.ops4j.pax.exam.junit.PaxExam$2.evaluate(PaxExam.java:294)<br /> at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)<br /> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:69)<br /> at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:48)<br /> at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)<br /> at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)<br /> at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)<br /> at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)<br /> at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)<br /> at org.junit.runners.ParentRunner.run(ParentRunner.java:292)<br /> at org.ops4j.pax.exam.junit.PaxExam.run(PaxExam.java:111)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:252)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:141)<br /> at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:112)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:189)<br /> at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:165)<br /> at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(ProviderFactory.java:85)<br /> at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:115)<br /> at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:75)

---

**Affects:** 3.0.1
Votes: 0, Watches: 0
