### ISSUE TITLE
Pax Exam TestNG fails with ClassNotFoundException for org.testng.Assert when TestNG version is 6.5 or newer [PAXEXAM-434]

### ISSUE THREAD

**Issue by ops4j-issues** [ops4j/org.ops4j.pax.exam2#560]
**[Oliver Lietz](https://ops4j1.jira.com/secure/ViewProfile.jspa?accountId=557058:a018e4d5-9bbe-4268-9ae9-2c253f8fe872)** created **[PAXEXAM-434](https://ops4j1.jira.com/browse/PAXEXAM-434)** 

2194 [main](https://ops4j1.jira.com/wiki/display/PAXEXAM/main) ERROR org.ops4j.pax.exam.testng.listener.PaxExam - Exception<br /> org.ops4j.pax.exam.TestContainerException: java.lang.reflect.InvocationTargetException<br /> at org.ops4j.pax.exam.raw.extender.intern.ProbeInvokerImpl.injectContextAndInvoke(ProbeInvokerImpl.java:134)<br /> at org.ops4j.pax.exam.raw.extender.intern.ProbeInvokerImpl.findAndInvoke(ProbeInvokerImpl.java:87)<br /> at org.ops4j.pax.exam.raw.extender.intern.ProbeInvokerImpl.call(ProbeInvokerImpl.java:74)<br /> at org.ops4j.pax.exam.nat.internal.NativeTestContainer.call(NativeTestContainer.java:95)<br /> at org.ops4j.pax.exam.spi.reactors.AllConfinedStagedReactor.invoke(AllConfinedStagedReactor.java:79)<br /> at org.ops4j.pax.exam.testng.listener.PaxExam.runByDriver(PaxExam.java:488)<br /> at org.ops4j.pax.exam.testng.listener.PaxExam.run(PaxExam.java:319)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.testng.internal.MethodInvocationHelper.invokeHookable(MethodInvocationHelper.java:194)<br /> at org.testng.internal.Invoker.invokeMethod(Invoker.java:694)<br /> at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:893)<br /> at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1218)<br /> at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)<br /> at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)<br /> at org.testng.TestRunner.privateRun(TestRunner.java:758)<br /> at org.testng.TestRunner.run(TestRunner.java:613)<br /> at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)<br /> at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)<br /> at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)<br /> at org.testng.SuiteRunner.run(SuiteRunner.java:240)<br /> at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)<br /> at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:87)<br /> at org.testng.TestNG.runSuitesSequentially(TestNG.java:1170)<br /> at org.testng.TestNG.runSuitesLocally(TestNG.java:1095)<br /> at org.testng.TestNG.run(TestNG.java:1007)<br /> at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:70)<br /> at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:109)<br /> at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:111)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(ReflectionUtils.java:164)<br /> at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke(ProviderFactory.java:110)<br /> at org.apache.maven.surefire.booter.SurefireStarter.invokeProvider(SurefireStarter.java:175)<br /> at org.apache.maven.surefire.booter.SurefireStarter.runSuitesInProcessWhenForked(SurefireStarter.java:107)<br /> at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:68)<br /> Caused by: java.lang.reflect.InvocationTargetException<br /> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)<br /> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)<br /> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)<br /> at java.lang.reflect.Method.invoke(Method.java:597)<br /> at org.ops4j.pax.exam.raw.extender.intern.ProbeInvokerImpl.injectContextAndInvoke(ProbeInvokerImpl.java:124)<br /> ... 39 more<br /> Caused by: java.lang.NoClassDefFoundError: org/testng/Assert<br /> at org.springextensions.db4o.BlueprintIT.testDb4oOperations(BlueprintIT.java:72)<br /> ... 44 more<br /> Caused by: java.lang.ClassNotFoundException: org.testng.Assert not found by PAXEXAM-PROBE-10909973-ebe2-4ee8-82ca-f82a39d67481 [26](https://ops4j1.jira.com/wiki/display/PAXEXAM/26)<br /> at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1460)<br /> at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:72)<br /> at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1843)<br /> at java.lang.ClassLoader.loadClass(ClassLoader.java:247)<br /> ... 45 more

works with TestNG 6.4

---

**Affects:** 3.0.0.M3
Votes: 0, Watches: 0
